### ISSUE TITLE
Mac OS X 在中文路径中运行报错

### ISSUE THREAD

**Issue by archtaurus** [archtaurus/BingWallpaper#1]
```
Traceback (most recent call last):
File "/Volumes/laozhao/壁纸/BingWallpaper.pyw", line 171, in save_today
  self.show_wall()
File "/Volumes/laozhao/壁纸/BingWallpaper.pyw", line 123, in show_wall
  wx.BITMAP_TYPE_JPEG)
File "/usr/local/lib/wxPython-3.0.2.0/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/
_core.py", line 2882, in __init__
  _core_.Image_swiginit(self,_core_.new_Image(*args, **kwargs))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 17: ordinal not in
range(128)
```

**Comment by archtaurus** [comment]
添加了以下代码问题解决了。
```
from __future__ import unicode_literals
import sys
reload(sys)
sys.setdefaultencoding('utf-8')
```
